unique_ids:
  assets:
    standard-page.html: 3T24SIWNT4K2O2BHAVL43AKW3F42Q5AY
    theme.css: W3YW4NVRVDD3VVEMAVSVT7HSU22MSSXB
  forms:
    Form1: G7GYMHZRNNHP36YVF3REWMXFI7T3W2XO
  modules: {}
  scripts: {}
  server_modules: {}
